services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jobs
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: